import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {GraphQLClient,gql} from "graphql-request"
import BlogCard from '../components/BlogCard'


const graphCms = new GraphQLClient('https://api-eu-central-1.graphcms.com/v2/cl5comd2q04or01ukh9pobhe9/master')

const QUERY = gql`
  query {
    posts{
      id
      title
      slug
      date_published
      content{
        html
      }
      cover_photo{
        url
      }
      author{
        name
        avatar{
          url
        }
      }
    }
  }
`

export async function getStaticProps() {
  const posts = await graphCms.request(QUERY)
  return {
    props: {
      posts : posts.posts
    },
    revalidate: 10
  }
}

export default function Home({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map((post) =>{
          console.log(post)
          return (
          <BlogCard
            key={post.id}
            title={post.title}
            slug={post.slug}
            content={post.content.html}
            author={post.author.name}
            avatar={post.author.avatar}
            cover={post.cover_photo}
            datePublished={post.date_published}
          />);
        })}
      </main>

    </div>
  )
}
